/**
 * Featured QA projects — real work, described honestly.
 *
 * Fields that were not provided in the brief are left empty and the UI renders
 * them as an explicit "[Add ...]" placeholder instead of inventing content.
 */

export const projects = [
  {
    id: 'thryve',
    name: 'Thryve Healthcare Platform',
    type: 'QA Project Case Study',
    context: 'Professional QA work',
    accent: 'health',
    description:
      'A healthcare platform involving patient onboarding, subscriptions, appointments, provider workflows, phlebotomy visits, lab orders, care plans, messaging, and AI-assisted patient features.',
    responsibilities: [
      'Testing patient, admin, provider and phlebotomist workflows',
      'Validating role-based access across each role',
      'End-to-end workflow testing across connected entities',
      'Data consistency checks between screens and layers',
      'Regression testing across releases',
      'Investigating and reporting defects with evidence',
    ],
    testingAreas: [
      'Patient workflows',
      'Admin workflows',
      'Provider workflows',
      'Phlebotomist workflows',
      'Subscription and credit management',
      'Appointment workflows',
      'Lab orders',
      'Patient assessments',
      'Messaging',
      'Care plans',
      'AI-generated lab summaries',
      'Patient CoPilot',
      'File uploads',
      'Notifications',
      'Document workflows',
      'Role-based access',
      'Data consistency',
      'Regression testing',
    ],
    keyScenarios: [
      'Each role can only reach the workflows it is authorised to use',
      'A subscription or credit change is reflected correctly in the related workflows',
      'An appointment moves through its states consistently for patient, provider and phlebotomist',
      'A lab order and its results stay consistent between the ordering and results views',
      'An assessment submission is stored and displayed consistently',
      'Messages reach the intended participant and only the intended participant',
      'A care plan reflects the data it is built from',
      'AI-generated lab summaries and Patient CoPilot responses match the underlying patient data',
      'File uploads and document workflows behave correctly for valid, oversized, unsupported and interrupted files',
      'Notifications reach the right role at the right step of a workflow',
      'Previously working flows still work after each release (regression)',
    ],
    challenges: [
      'Four distinct roles — patient, admin, provider and phlebotomist — each with its own workflows and permission boundaries',
      'Workflows depend on state: an appointment, lab order or care plan only behaves correctly when the previous step completed',
      'Subscription and credit management affects what a user can do elsewhere in the platform',
      'Many interconnected entities mean one change can affect several screens, so data consistency has to be verified end to end',
      'AI-assisted features (lab summaries, Patient CoPilot) need to be checked against the real patient data behind them',
      'File handling and messaging introduce inputs that vary by user, network and file type',
    ],
    learned: [
      'How to structure testing around roles and permissions rather than around screens',
      'Why end-to-end walkthroughs matter when entities depend on each other’s state',
      'How to validate AI-generated output against the source data it summarises',
      'Why regression scope has to be chosen deliberately in a platform with many connected workflows',
    ],
    tools: [], // not specified — rendered as a placeholder in the UI
    workflow: {
      title: 'Patient journey used to plan end-to-end coverage',
      steps: [
        'Patient Signup',
        'Package Purchase',
        'Intake Assessment',
        'Provider Consultation',
        'Lab / Order',
        'Phlebotomy',
        'Results',
        'Care Plan',
      ],
    },
  },
  {
    id: 'flit',
    name: 'Flit AI Recruiting Platform',
    type: 'QA Project Case Study',
    context: 'Professional QA work',
    accent: 'recruit',
    description:
      'An AI-powered recruiting platform involving candidates, employees, job recommendations, profiles, hiring workflows, interviews, and candidate selection.',
    responsibilities: [
      'Testing authentication and candidate profile creation',
      'Validating CV parsing output against the uploaded document',
      'Testing job recommendation and employer/hiring workflows',
      'API validation against the documented contract',
      'UI, negative and regression testing',
    ],
    testingAreas: [
      'Registration',
      'Authentication',
      'Candidate profile creation',
      'CV parsing and AI-powered CV generation',
      'Job posting',
      'Job recommendations',
      'Candidate management',
      'Employer workflows',
      'Hiring workflows',
      'Interview scheduling',
      'Video introduction',
      'API validation',
      'UI testing',
      'Negative testing',
      'Regression testing',
    ],
    keyScenarios: [
      'A candidate can register, sign in and sign out, and invalid credentials are rejected',
      'A completed candidate profile produces the recommendations expected for that profile',
      'CV parsing and AI-powered CV generation reflect the content of the uploaded CV',
      'A posted job is visible and behaves correctly for matching candidates',
      'Interview scheduling keeps candidate and employer views consistent',
      'An employer can move a candidate through the hiring workflow',
      'A video introduction is recorded, stored and played back for the right candidate',
      'API responses match the documented contract in shape, status code and content',
      'Invalid, missing, oversized or malformed input is rejected with clear feedback',
      'Previously working flows still work after each release (regression)',
    ],
    challenges: [
      'Two very different user types — candidates and employers — with separate journeys that meet in the hiring workflow',
      'CV parsing and job recommendations depend on user-supplied content, so expected results have to be judged against the input',
      'Video introduction testing covers capture, storage and playback across browsers',
      'UI behaviour had to be cross-checked against the API to separate a display issue from a data issue',
    ],
    learned: [
      'How to separate a UI defect from an API or data defect using response inspection',
      'How to design negative scenarios for input-driven features such as CV parsing',
      'How to keep regression scope focused when features feed into each other',
    ],
    tools: ['Postman', 'Swagger', 'Playwright', 'Browser developer tools'],
    pipeline: {
      title: 'How each feature moved through the QA lifecycle',
      steps: [
        'Requirement',
        'Test Strategy',
        'Test Scenarios',
        'Execution',
        'Defect Detection',
        'Retesting',
        'Regression',
      ],
    },
  },
  {
    id: 'qualityguard',
    name: 'QualityGuard',
    type: 'QA Automation / Learning Project',
    context: 'Personal project — not a production system',
    accent: 'automation',
    description:
      'A QA-focused automation and learning project built to practise designing automated browser tests in a reusable, maintainable way with Python and Playwright.',
    responsibilities: [
      'Designing a reusable test structure instead of one-off scripts',
      'Writing automated browser tests for login and related flows',
      'Managing test data separately from test logic',
      'Writing assertions that fail for the right reason',
      'Covering negative scenarios and regression paths',
    ],
    testingAreas: [
      'Automated browser testing',
      'Reusable test structure',
      'Test data',
      'Assertions',
      'Login testing',
      'Negative scenarios',
      'Regression automation',
    ],
    keyScenarios: [
      'A valid login reaches the expected destination',
      'An invalid username, invalid password or empty field is rejected with clear feedback',
      'The same test data set can be reused across runs without leaving the app in a broken state',
      'A previously automated flow still passes after a change (regression run)',
      'A failing assertion reports what was expected versus what happened',
    ],
    challenges: [
      'Keeping tests independent so one failure does not cascade into the rest of the run',
      'Separating test data, page interactions and assertions so tests stay readable',
      'Writing assertions that describe intent instead of implementation detail',
    ],
    learned: [
      'How a small amount of structure makes automated tests far easier to maintain',
      'How to design negative scenarios that are worth automating',
      'Why regression automation pays off only when the suite stays stable and readable',
    ],
    tools: ['Python', 'Playwright'],
    stackNote: 'Primary technology: Python + Playwright',
  },

  {
    id: 'lifeweaver',
    name: 'LifeWeaver — AI-Powered Platform',
    type: 'QA Project Case Study',
    context: 'Professional QA work',
    accent: 'ai',
    description:
      'An AI-powered platform combining LLM functionality with backend API integrations to external services such as WhatsApp, Gmail, and Google Calendar.',
    responsibilities: [
      'QA across core functional and integration workflows',
      'Testing AI/LLM functionality and backend API integrations',
      'Validating integrations with WhatsApp, Gmail, and Calendar',
      'Executing API, database, functional, and end-to-end test scenarios',
      'Identifying, documenting, and retesting defects',
    ],
    testingAreas: [
      'AI/LLM functionality',
      'Backend API integrations',
      'WhatsApp integration',
      'Gmail integration',
      'Google Calendar integration',
      'API testing',
      'Database testing',
      'Functional testing',
      'End-to-end testing',
      'Defect retesting',
    ],
    keyScenarios: [
      'Each external integration (WhatsApp, Gmail, Calendar) sends and receives the data the workflow expects',
      'AI/LLM responses are consistent with the input and the connected data',
      'Data created through an integration is stored consistently in the backend',
      'A failure in an external service produces a clear, recoverable state in the platform',
      'Previously working flows still pass after changes (regression)',
    ],
    challenges: [
      'Behaviour depends on third-party services as well as the platform itself, so defects had to be isolated layer by layer',
      'AI-powered responses had to be validated against the intent and data behind each request',
      'Integration issues can be intermittent, so reproduction notes and evidence mattered even more',
    ],
    learned: [
      'How to test a system whose behaviour crosses into third-party services',
      'How to structure evidence for integration defects so developers can act on it',
      'How to validate AI-powered features end to end, from input to stored result',
    ],
    tools: [], // not specified — rendered as a placeholder in the UI
  },
];